# This is a basic workflow to help you get started with Actions

name: Deploy on release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout Main
        uses: actions/checkout@v6

      # Install PNPM
      - name: Install PNPM
        uses: pnpm/action-setup@v6
        with:
          run_install: true

      - name: Set up Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install deps
        run: pnpm install

      - name: Build the project
        run: pnpm generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          # github will auto-generate a token for this job and use it
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.output/public
          force_orphan: true
